# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: nglynis <marvin@42.fr>                     +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/11/14 21:57:43 by nglynis           #+#    #+#              #
#    Updated: 2019/11/15 17:16:49 by nglynis          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


all:
	gcc -Wall -Wextra -Werror fillit.c main.c getNextLine/get_next_line.c -L getNextLine/libft -lft getNextLine/libft/libft.h
